### ISSUE TITLE
Base not working.

### ISSUE THREAD

**Issue by nonolk** [gilmrt/Domoticz-Botvac-Plugin#1]
Hello,

First of all very nice work. I’m juste facing one issue, indeed the base setting do not work.
When I select it nothing happen. All other parameters are working.

Best regards,

**Comment by gilmrt** [comment]
The base (return back to base) command only works during a started clean session from the base.
If the previous state was stopped or paused or resumed, it’s no more working.
This is not so great but it’s a limitation of the APIs
