### ISSUE TITLE
Just a small readme change

### ISSUE THREAD

**Issue by JayPe69** [gilmrt/Domoticz-Botvac-Plugin#2]
First of all, a big thanks for this plugin 👍 
it works like a charm.

By following your readme, I guess you should add a : restart after installing the plugin. (you add it after update, but not after installation).

Again, thanks a lot

**Comment by gilmrt** [comment]
> First of all, a big thanks for this plugin 👍
> it works like a charm.
> 
> By following your readme, I guess you should add a : restart after installing the plugin. (you add it after update, but not after installation).
> 
> Again, thanks a lot

Thanks for your comment. Restart step is now added in the installation process of the README.md

**Comment by gilmrt** [comment]
Restart step added
