### ISSUE TITLE
Error on add my vaccum to hardware

### ISSUE THREAD

**Issue by 18David** [gilmrt/Domoticz-Botvac-Plugin#4]
I got this error then I try to add my vaccum to domoticz 

> 2020-12-09 20:18:18.256 Status: (Botvac Vaccum) Started.
> 2020-12-09 20:18:19.910 Status: (Botvac Vaccum) Entering work loop.
> 2020-12-09 20:18:19.911 Status: (Botvac Vaccum) Initialized version 1.2.0, author 'gilmrt'
> 2020-12-09 20:18:19.913 Error: (Botvac Vaccum) 'onStart' failed 'TypeError':'__init__() takes 2 positional arguments but 3 were given'.
> 2020-12-09 20:18:19.913 Error: (Botvac Vaccum) ----> Line 279 in '/home/pi/domoticz/plugins/Domoticz-Botvac-Plugin/plugin.py', function onStart
> 2020-12-09 20:18:19.913 Error: (Botvac Vaccum) ----> Line 120 in '/home/pi/domoticz/plugins/Domoticz-Botvac-Plugin/plugin.py', function onStart

**Comment by gilmrt** [comment]
@18David 
Can you confirm you entered your email address (used for neato account) in the username field without any additional space ?
It looks like your password contains a space or comma and the system consider it as a third parameter in the initialization function. 
Please confirm, if so I will try to take these special characters in charge

**Comment by 18David** [comment]
I double check and there is no space in the field. And I don't have any special characters in my password.

**Comment by gilmrt** [comment]
Ok I got it !
The pybotvac lib was updated last week and plugin need some changes on my side
You can bypass using a simple command on your domoticz system:
`pip3 install --upgrade pybotvac==0.0.17` to use the previous version of pybotvac
I will update the README as well
Thanks for you report

**Comment by 18David** [comment]
Thank's for your help ! It's working perfectly  !

**Comment by gilmrt** [comment]
You can now update all plugin and pybotvac lib if you want by using
`git pull` in the plugin folder and 
`pip3 install --upgrade pybotvac==0.0.19`
but it's not mandatory

Update to pybotvac 0.0.19 merged [PR#5](https://github.com/gilmrt/Domoticz-Botvac-Plugin/pull/5)
